# Generated by Django 6.0 on 2026-01-12 15:14

from django.db import migrations

DEFAULT_TAGS = ["учеба", "работа", "продукты"]


def seed_tags(apps, schema_editor):
    Tag = apps.get_model("notes", "Tag")
    for name in DEFAULT_TAGS:
        Tag.objects.get_or_create(name=name)


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model("notes", "Tag")
    Tag.objects.filter(name__in=DEFAULT_TAGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_tag_note_tags"),
    ]

    operations = [
        migrations.RunPython(seed_tags, reverse_code=unseed_tags),
    ]
